config/routes.rb
# Copyright (C) 2010-2012, InSTEDD
#
# This file is part of Verboice.
#
# Verboice is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Verboice is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Verboice.  If not, see <http://www.gnu.org/licenses/>.

require 'api_constraints'

Verboice::Application.routes.draw do

  resources :call_log_recorded_audios, only: [:update]

  resources :channels do
    resources :queued_calls
    member do
      get :call
    end
  end

  resources :nuntium_channels, except: [:show]

  match '/' => 'home#index',  :as => 'home'

  devise_for :accounts

  resources :feeds, controller: :feed_server do
    member do
      get :recordings
      get 'recording/:recording_id', action: :get_recording, as: :recording
    end
  end

  # Register both shallow and deep routes:
  # - Shallow routes allow for easier path helper methods, such as contact_recorded_audios(@contact) instead of project_contact_recorded_audios(@project, @contact)
  # - Deep routes ensure that form_for directives work as expected, so form_for([@project, @contact]) works no matter it is a creation or an update
  [true, false].each do |shallow|
    resources :projects, :shallow => shallow do
      member do
        post :enqueue_call
        put :update_variables
      end
      

      resources :call_flows, except: [:new, :edit] do
        member do
          get :edit_workflow, path: :designer
          put :update_workflow, path: :update_flow
          post :import
          get :export
          get :download_results
          get :oauth
        end
      end

      resources :external_services, except: [:show, :new, :edit] do
        member do
          put :update_manifest
        end
      end

      resources :schedules

      resources :contacts, except: [:show] do
        get :invitable, on: :collection
      end

      resources :resources do
        collection do
          get :find
        end

        resources :localized_resources do
          member do
            post :save_recording
            get :play_recording
            post :save_file
            get :play_file
          end
        end
      end

      resources :feeds
      
      resources :call_logs, :path => :calls, :only => :index do |r|
        collection do
          get :download, to: 'call_logs#download_project_call_logs'
          get :generate_zip
          get :download_zip
        end
      end

      resources :feeds
    end
  end

  resources :call_logs, path: :calls do
    member do
      get :progress
      get 'results/:key', :action => :play_result, :as => 'result'
      get :download_details
    end
    collection do
      get :queued
      put :queued_paused
      put :queued_resumed
      get :download
    end
  end

  namespace :ext do 
    namespace :services do
      resources :pregnancies do
        collection do
          get :manifest
          post :register
          post :progress
        end
      end
    end

    resources :projects do
      resources :reminder_groups, :only => [:index] do
        post :import, :on => :member
      end

      resources :reminder_schedules do
        get :references_data, :on => :collection
        post 'remove_reminder_channel'
        collection do
          get 'channels_autocomplete'
        end
      end

      resources :pregnancy_reminders
    end
  end  
    

  resource :synthesizer do
    get :voices
  end

  namespace :api, defaults: {format: 'json'} do
    match "call" => "calls#call"
    resources :calls, only: [] do
      member do
        match :state
        match :redirect
      end
    end
    get "channels" => "channels#list"
    resources :channels, only: [:create] do
      collection do
        get ":name", :action => "get"
        put ":name", :action => "update"
        delete ":name", :action => "destroy"
      end
    end
    resources :projects, only: [:index] do
      resources :contacts, only: [:index, :create] do
        collection do
          get 'by_address/:address', :action => "show_by_address"
          put 'by_address/:address', :action => "update_by_address"
          put 'all', :action => "update_all"
          delete :unregistration
        end
      end
      resources :schedules, only: [:index, :create] do
        collection do
          get ':name', :action => "show"
          put ':name', :action => "update"
          delete ':name', :action => "destroy"
        end
      end

      resources :reminder_groups, only: [:index, :create, :update, :destroy], shallow: true
    end

    resources :logs, only: [] do
      collection do
        get ':call_id', action: :list
      end
    end

    get '/contacts/:address/call_logs', controller: :call_logs, action: :index
    resources :call_logs, only: [:index, :show]

    get "call_flows" => "call_flows#list"
  end

  namespace :api2, defaults: {format: 'json'} do

    match "call" => "calls#call"
    resources :calls, only: [] do
      member do
        match :state
        match :redirect
      end
    end

    resources :channels, only: [:create, :index] do
      collection do
        get ":name", :action => "get"
        put ":name", :action => "update"
        delete ":name", :action => "destroy"
      end
    end
    resources :projects, only: [:index] do
      resources :contacts, only: [:index, :create] do
        collection do
          get 'by_address/:address', :action => "show_by_address"
          put 'by_address/:address', :action => "update_by_address"
          put 'all', :action => "update_all"
          delete :unregistration
        end
      end
      resources :schedules, only: [:index, :create] do
        collection do
          get ':name', :action => "show"
          put ':name', :action => "update"
          delete ':name', :action => "destroy"
        end
      end

      resources :reminder_groups, only: [:index, :create, :update, :destroy], shallow: true
    end

    resources :logs, only: [] do
      collection do
        get ':call_id', action: :list
      end
    end

    get '/channels/:channel_id/call_logs' => "call_logs#list_by_channel"
    get '/contacts/:address/call_logs', controller: :call_logs, action: :index
    resources :call_logs, only: [:index, :show]

    get "call_flows" => "call_flows#list"

    get "accounts" => "accounts#index"

    post '/auth' => 'sessions#create'

    resources :traffics, only: [:index]
  end

  post 'call_simulator/start'
  post 'call_simulator/resume'

  get 'oauth/google' => 'oauth#google', :as => 'google_oauth'
  match 'oauth/google/callback' => 'oauth#google_callback', :as => 'google_callback_oauth'

  root :to => 'home#index'

  get 'terms_and_conditions', :to => redirect('/')
end

app/controllers/api/call_logs_controller.rb
# Copyright (C) 2010-2012, InSTEDD
#
# This file is part of Verboice.
#
# Verboice is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Verboice is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Verboice.  If not, see <http://www.gnu.org/licenses/>.
module Api
  class CallLogsController < ApiController
    before_filter :verify_request, :except => [:index]

    # GET /contacts/:address/call_logs
    # GET /call_logs
    def index
      @call_logs = current_account.call_logs
      @call_logs = @call_logs.where(address: params[:address]) if params[:address]
      render json: @call_logs, root: false
    end

    # GET /call_logs/:id
    def show
      render json: @call_log
    end

    private
    def verify_request
      begin
        @call_log = current_account.call_logs(true).find(params[:id])
      rescue
        render json: "The call log is not found".to_json, status: :not_found
        return
      end
    end
  end
end

app/controllers/api/projects_controller.rb
# Copyright (C) 2010-2012, InSTEDD
#
# This file is part of Verboice.
#
# Verboice is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Verboice is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Verboice.  If not, see <http://www.gnu.org/licenses/>.
module Api
  class ProjectsController < ApiController

    # GET /api/projects
    def index
      projects = Project.all if current_account.admin?
      projects = current_account.projects if current_account.user?
      render json: projects, root: false
    end
  end
end

app/controllers/api2/call_logs_controller.rb
# Copyright (C) 2010-2012, InSTEDD
#
# This file is part of Verboice.
#
# Verboice is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Verboice is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Verboice.  If not, see <http://www.gnu.org/licenses/>.
module Api2
  class CallLogsController < Api2Controller
    before_filter :verify_request, :only => [:show]
    before_filter :filter, :only => [:list_by_channel]

    # GET /call_logs
    def index
      if api_current_account.admin?
        if api_current_account.has_access_from?(origin_host)
          @call_logs = CallLog.where("1=1")
          @call_logs = @call_logs.by_account_id(params[:account_id]) if params[:account_id] 
          @call_logs = @call_logs.by_channel_id(params[:channel_id]) if params[:channel_id] 
          @call_logs = @call_logs.between(params[:start_date], params[:end_date])
        else
          return head :unauthorized
        end
      else
        @call_logs = api_current_account.call_logs
        @call_logs = @call_logs.where(address: params[:address]) if params[:address]
      end

      @call_logs = @call_logs.includes([:account, :channel, :project])

      render json: @call_logs, each_serializer: CustomCallLogSerializer
    end

    # GET /call_logs/:id
    def show
      render json: @call_log, serializer: CustomCallLogSerializer
    end

    # GET /channels/:channel_id/call_logs
    def list_by_channel
      render json: @call_logs, each_serializer: CustomCallLogSerializer
    end

    private

    def verify_request
      begin
        @call_log = api_current_account.call_logs.find(params[:id])
      rescue
        head :not_found
        return
      end
    end

    def filter
      status_code = nil
      if api_current_account.admin? && api_current_account.has_access_from?(origin_host)
        @channel = Channel.find(params[:channel_id]) rescue status_code = :not_found
      else
        @channel = api_current_account.channels.find(params[:channel_id]) rescue status_code = :unauthorized
      end

      return head status_code if status_code

      @call_logs = @channel.call_logs

      if params[:start_date].present? && params[:end_date].present?
        @call_logs = @call_logs.between(params[:start_date],params[:end_date])
      end

      @call_logs

    end

  end
end

app/controllers/api2/projects_controller.rb
# Copyright (C) 2010-2012, InSTEDD
#
# This file is part of Verboice.
#
# Verboice is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Verboice is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Verboice.  If not, see <http://www.gnu.org/licenses/>.
module Api2
  class ProjectsController < Api2Controller

    # GET /api/projects
    def index
      projects = Project.all if api_current_account.admin?
      projects = api_current_account.projects if api_current_account.user?
      render json: projects, root: false
    end
  end
end

app/helpers/call_log_helper.rb
# Copyright (C) 2010-2012, InSTEDD
#
# This file is part of Verboice.
#
# Verboice is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Verboice is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Verboice.  If not, see <http://www.gnu.org/licenses/>.

module CallLogHelper
  def render_csv_download? project_id, search = nil
    logs = CallLog.where project_id: project_id
    logs = logs.search search
    audios = CallLogRecordedAudio.where call_log_id: logs 

    logs.count > CallLog::CSV_MAX_ROWS || audios.count == 0
  end
end

app/helpers/project_helper.rb
# Copyright (C) 2010-2012, InSTEDD
#
# This file is part of Verboice.
#
# Verboice is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Verboice is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Verboice.  If not, see <http://www.gnu.org/licenses/>.

module ProjectHelper

  def project_languages_json(project)
    project.languages.map { |lang| {key: lang['language'], value: LanguageList::LanguageInfo.find(lang['language']).name} }.to_json
  end

  def call_flows_options(project)
    all_call_flow = [t('views.projects.call_logs.index.label.all_call_flow'), nil]
    options = project.call_flows.map { |c| [c.name, c.id] }.insert 0, all_call_flow
    options
  end
end

app/views/projects/call_logs/index.html.haml
= render 'shared/project_tabs_and_title', :project => @project

%h1= t('views.projects.call_logs.index.label.calls')
%p.desc= t('views.projects.call_logs.index.label.desc')

= render 'search', project: @project

-unless @logs.empty?
  %p
    - if render_csv_download? @project, @search
      = link_to t('views.call_logs.index.action.download_csv'), download_project_call_logs_path(format: :csv, search: @search), :class => "button fimport"
    - else
      = link_to t('views.call_logs.index.action.download_csv'), download_project_call_logs_path(search: @search), :class => %w(button fimport download-call_logs)
%br/
%div= page_entries_info @logs, :entry_name => t('views.projects.call_logs.index.label.call_log')
= will_paginate @logs, :param_name => 'page'
- if @logs.present?
  %br/
  %table.GralTable
    %tr
      %th= t('views.projects.call_logs.index.label.id')
      %th= t('views.projects.call_logs.index.label.started')
      %th= t('views.projects.call_logs.index.label.finished')
      %th= t('views.projects.call_logs.index.label.duration_in_second')
      %th= t('views.projects.call_logs.index.label.caller_id')
      %th= t('views.projects.call_logs.index.label.direction')
      %th= t('views.projects.call_logs.index.label.number_retried')
      %th= t('views.projects.call_logs.index.label.channel')
      %th= t('views.projects.call_logs.index.label.project')
      %th= t('views.projects.call_logs.index.label.call_flow')
      %th= t('views.projects.call_logs.index.label.status')
      %th= t('views.projects.call_logs.index.label.interaction')
      - @project.project_variables.each do |variable|
        %th= variable.try(:name)
      %th
    - @logs.each do |log|
      %tr
        %td= log.id
        %td= datetime_format log.created_at, @project.time_zone
        %td= datetime_format log.finished_at, @project.time_zone
        %td= log.duration if log.duration && log.duration > 0
        - if log.address.present?
          %td= link_to log.address_without_prefix, call_logs_path(:search => "caller:#{log.address_without_prefix}")
        - else
          %td= log.address
        %td= log.direction
        %td= log.retries if log.retries && log.retries > 0
        %td= log.channel.try(:name)
        %td= log.project.try(:name)
        %td= log.call_flow.try(:name)
        %td
          - if log.state == CallLog::STATE_FAILED
            = CallLog::FAIL_REASONS[log.fail_reason]
          - else
            = log.state

        %td= log.step_interaction
        - @project.project_variables.each do |variable|
          - existed = false
          - log.call_log_answers.each do |answer|
            - if answer.project_variable && answer.project_variable.id == variable.id
              - existed = true
              %td= answer.try(:value)
              - break
          - log.call_log_recorded_audios.each do |recorded_audio|
            - if recorded_audio.project_variable_id == variable.id
              - existed = true
              %td{ id: "audio_#{recorded_audio.id}" }
                .audio-annotation
                  .modal{ id: "audio_annotation_#{recorded_audio.id}" }
                    %h2= t('views.call_logs.index.label.annotation')
                    %audio.recorded-audio{ controls: "", data: { audio_id: recorded_audio.id } }
                      %source{ src: result_call_log_path(recorded_audio.call_log, { key: recorded_audio.key }) + ".wav", type: "audio/wav" }
                        Your browser does not support the audio element.
                    %br/
                    %textarea{ rows: 5, data: { annotation: recorded_audio.annotation } }= recorded_audio.annotation
                    %br/
                    %button.white.save-annotation= t('views.form.save')
                    %a.cancel-edit-annotation{ href: "Javascript:void(0);" }= t('views.form.close')
                .div_content_variable
                  .div_left
                    %a.fplay.audio-control{ href: "Javascript:void(0);" }
                  .div_right
                    %a.fimport{ href: result_call_log_path(recorded_audio.call_log, {:key => recorded_audio.key}) }
                    %a.fancybox.icon_button{ class: recorded_audio.annotation.present? ? "fedit-blue" : "fedit", href: "#audio_annotation_#{recorded_audio.id}" }
          - unless existed
            %td
        %td= link_to(t('views.projects.call_logs.index.action.view_details'), call_log_path(log)) if log.store_log_entries
  %br/
  %div= page_entries_info @logs, :entry_name => t('views.projects.call_logs.index.label.call_log')
  = will_paginate @logs, :param_name => 'page'
%br/