config/routes.rb
# Copyright (C) 2010-2012, InSTEDD
#
# This file is part of Verboice.
#
# Verboice is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Verboice is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Verboice.  If not, see <http://www.gnu.org/licenses/>.

require 'api_constraints'

Verboice::Application.routes.draw do

  resources :call_log_recorded_audios, only: [:update]

  resources :channels do
    resources :queued_calls
    member do
      get :call
    end
  end

  resources :nuntium_channels, except: [:show]

  match '/' => 'home#index',  :as => 'home'

  devise_for :accounts

  resources :feeds, controller: :feed_server do
    member do
      get :recordings
      get 'recording/:recording_id', action: :get_recording, as: :recording
    end
  end

  # Register both shallow and deep routes:
  # - Shallow routes allow for easier path helper methods, such as contact_recorded_audios(@contact) instead of project_contact_recorded_audios(@project, @contact)
  # - Deep routes ensure that form_for directives work as expected, so form_for([@project, @contact]) works no matter it is a creation or an update
  [true, false].each do |shallow|
    resources :projects, :shallow => shallow do
      member do
        post :enqueue_call
        put :update_variables
      end
      

      resources :call_flows, except: [:new, :edit] do
        member do
          get :edit_workflow, path: :designer
          put :update_workflow, path: :update_flow
          post :import
          get :export
          get :download_results
          get :oauth
        end
      end

      resources :external_services, except: [:show, :new, :edit] do
        member do
          put :update_manifest
        end
      end

      resources :schedules

      resources :contacts, except: [:show] do
        get :invitable, on: :collection
      end

      resources :resources do
        collection do
          get :find
        end

        resources :localized_resources do
          member do
            post :save_recording
            get :play_recording
            post :save_file
            get :play_file
          end
        end
      end

      resources :feeds
      
      resources :call_logs, :path => :calls, :only => :index do |r|
        collection do
          get :download, to: 'call_logs#download_project_call_logs'
          get :generate_zip
          get :download_zip
        end
      end

      resources :feeds
    end
  end

  resources :call_logs, path: :calls do
    member do
      get :progress
      get 'results/:key', :action => :play_result, :as => 'result'
      get :download_details
    end
    collection do
      get :queued
      put :queued_paused
      put :queued_resumed
      get :download
    end
  end

  namespace :ext do 
    namespace :services do
      resources :pregnancies do
        collection do
          get :manifest
          post :register
          post :progress
        end
      end
    end

    resources :projects do
      resources :reminder_groups, :only => [:index] do
        post :import, :on => :member
      end

      resources :reminder_schedules do
        get :references_data, :on => :collection
        post 'remove_reminder_channel'
        collection do
          get 'channels_autocomplete'
        end
      end

      resources :pregnancy_reminders
    end
  end  
    

  resource :synthesizer do
    get :voices
  end

  namespace :api, defaults: {format: 'json'} do
    match "call" => "calls#call"
    resources :calls, only: [] do
      member do
        match :state
        match :redirect
      end
    end
    get "channels" => "channels#list"
    resources :channels, only: [:create] do
      collection do
        get ":name", :action => "get"
        put ":name", :action => "update"
        delete ":name", :action => "destroy"
      end
    end
    resources :projects, only: [:index] do
      resources :contacts, only: [:index, :create] do
        collection do
          get 'by_address/:address', :action => "show_by_address"
          put 'by_address/:address', :action => "update_by_address"
          put 'all', :action => "update_all"
          delete :unregistration
        end
      end
      resources :schedules, only: [:index, :create] do
        collection do
          get ':name', :action => "show"
          put ':name', :action => "update"
          delete ':name', :action => "destroy"
        end
      end

      resources :reminder_groups, only: [:index, :create, :update, :destroy], shallow: true
    end

    resources :logs, only: [] do
      collection do
        get ':call_id', action: :list
      end
    end

    get '/contacts/:address/call_logs', controller: :call_logs, action: :index
    resources :call_logs, only: [:index, :show]

    get "call_flows" => "call_flows#list"
  end

  namespace :api2, defaults: {format: 'json'} do

    match "call" => "calls#call"
    resources :calls, only: [] do
      member do
        match :state
        match :redirect
      end
    end

    resources :channels, only: [:create, :index] do
      collection do
        get ":name", :action => "get"
        put ":name", :action => "update"
        delete ":name", :action => "destroy"
      end
    end
    resources :projects, only: [:index] do
      resources :contacts, only: [:index, :create] do
        collection do
          get 'by_address/:address', :action => "show_by_address"
          put 'by_address/:address', :action => "update_by_address"
          put 'all', :action => "update_all"
          delete :unregistration
        end
      end
      resources :schedules, only: [:index, :create] do
        collection do
          get ':name', :action => "show"
          put ':name', :action => "update"
          delete ':name', :action => "destroy"
        end
      end

      resources :reminder_groups, only: [:index, :create, :update, :destroy], shallow: true
    end

    resources :logs, only: [] do
      collection do
        get ':call_id', action: :list
      end
    end

    get '/channels/:channel_id/call_logs' => "call_logs#list_by_channel"
    get '/contacts/:address/call_logs', controller: :call_logs, action: :index
    resources :call_logs, only: [:index, :show]

    get "call_flows" => "call_flows#list"

    get "accounts" => "accounts#index"

    post '/auth' => 'sessions#create'

    resources :traffics, only: [:index]
  end

  post 'call_simulator/start'
  post 'call_simulator/resume'

  get 'oauth/google' => 'oauth#google', :as => 'google_oauth'
  match 'oauth/google/callback' => 'oauth#google_callback', :as => 'google_callback_oauth'

  root :to => 'home#index'

  get 'terms_and_conditions', :to => redirect('/')
end

app/controllers/home_controller.rb
# Copyright (C) 2010-2012, InSTEDD
# 
# This file is part of Verboice.
# 
# Verboice is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Verboice is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Verboice.  If not, see <http://www.gnu.org/licenses/>.

class HomeController < ApplicationController
  def index
    set_fixed_width_content
  end
end

app/views/home/index.haml
.homepage
  .right
    .illustration
    %a.button.fpdf.right{:href => "/docs/instedd-verboice.pdf", :target=>"_blank"}
      = "#{t('views.home.download_brochure')} (480 KB)"
  %h1.home= t('views.home.listen_and_response')
  %p.sub= t('views.home.listen_and_response_sub')
  %p= t('views.home.listen_and_response_body')

  %br/
  %br/
  %br/
  %br/
  %br/
  - if current_account
    %p
      = "#{t('views.home.get_started')}:"
      =link_button_to t('views.home.view_your_project'), projects_path, :class => "orange"
    %p
  - else
    %p
      = "#{t('views.home.get_started')}:"
      = link_button_to t('views.home.create_an_account'), new_account_registration_path, :class => "orange"
    %p
    %p
      = t('views.home.already_a_member')
      = link_to t('views.home.log_in'), new_account_session_path
  .clear
  / #container
  .home-middle-bar
    .benefits
      %ul#benefits-container
        %li
          %span.i48grad-language.left
          %h3= t('views.home.overcome')
          %p= t('views.home.literacy_barriers_with_verbal_communication')
          %br{:clear => "all"}/
        %li
          %span.i48grad-sound.left
          %h3= t('views.home.create')
          %p= t('views.home.voice_based_programs_without_coding')
          %br{:clear => "all"}/
        %li
          %span.i48grad-scale.left
          %h3= t('views.home.scales')
          %p= t('views.home.to_suit_your_needs')
          %br{:clear => "all"}/
        %li
          %span.i48grad-computer.left
          %h3= t('views.home.generate')
          %p= t('views.home.project_using_any_computer_with_internet_access')
          %br{:clear => "all"}/
        %li
          %span.i48grad-users.left
          %h3= t('views.home.reach')
          %p= t('views.home.out_to_any_community_anywhere_there_access_to_basic_phones')
          %br{:clear => "all"}/
        %li
          %span.i48grad-shred.left
          %h3= t('views.home.api')
          %p= t('views.home.based_on_standards')
          %br{:clear => "all"}/
        %li
          %span.i48grad-free.left
          %h3= t('views.home.free')
          %p= t('views.home.for_anyone_to_use_to_help_increase_their_social_impact')
          %br{:clear => "all"}/
        %li
          %span.i48grad-openSource.left
          %h3= t('views.home.open_source')
          %p= t('views.home.code_for_developers_to_use_to_improve_its_design_and_functionality')
          %br{:clear => "all"}/
      / #benefits-container
    / #benefits
  / #home-middle-bar
  #container
    %h1= t('views.home.container_first_title')
    %p.desc
      = t('views.home.container_first_desc')
    .left.w45
      %h2= t('views.home.container_first_panel_first_title')
      .icon-container.left
        %span.i96grad-medicine
      %p= t('views.home.container_first_panel_first_desc')
    / #left w45
    .right.w45
      %h2= t('views.home.container_first_panel_second_title')
      .icon-container.left
        %span.i96grad-pieChart
      %p= t('views.home.container_first_panel_second_desc')
    / #left w45
    .clear
    / #clear
    %br/
    .left.w45
      %h2= t('views.home.container_first_panel_third_title')
      .icon-container.left
        %span.i96grad-fire
      %p= t('views.home.container_first_panel_third_desc')
    / #left w45
    .right.w45
      %h2= t('views.home.container_first_panel_fourth_title')
      .icon-container.left
        %span.i96grad-tree
      %p= t('views.home.container_first_panel_fourth_desc')
    / #left w45
    .clear
    / #clear
    %br/
    .box.plain.grey.features

      %h2= t('views.home.container_features_title')
      %br
      .left.w45
        %div
          %span.r-arrow>
          = t('views.home.container_features_point_one')
        %div
          %span.r-arrow>
          = t('views.home.container_features_point_two')
        %div
          %span.r-arrow>
          = t('views.home.container_features_point_three')


      / #left w45
      .right.w45
        %div
          %span.r-arrow>
          = t('views.home.container_features_point_four')
        %div
          %span.r-arrow>
          = t('views.home.container_features_point_five')
        %div
          %span.r-arrow>
          = t('views.home.container_features_point_six')
        %div
          %span.r-arrow>
          = t('views.home.container_features_point_senven')
      / #right w45
      .clear
      / #clear
    / #box plain grey
    %br/
    %br/
    .w45.left
      %h1= t('views.home.container_second_title')

      %p= t('views.home.container_second_desc')
    / #w45 left
    .w45.right
      = image_tag 'infographic.png', :localized => true
    / #w45 right
    .clear
    / #clear
    %br/
    %br/
    #container
    %h1= t('views.home.container_third_title')

    .left.w45
      %h2= t('views.home.container_third_panel_first_title')
      .icon-container.left
        %span.i96-council
      %p
        = t('views.home.container_third_panel_first_desc')
        = link_to "http://www.babymonitor.co/", "http://www.babymonitor.co/"
    / #left w45
    .right.w45
      %h2= t('views.home.container_third_panel_second_title')
      .icon-container.left
        %span.i96-cross
      %p= t('views.home.container_third_panel_second_desc')
    / #left w45
    .clear
    / #clear

    %br/
    %hr/
    %div.w45.support
      %h2
        = t('views.home.container_fouth_title')
      %span
      %p
        = t('views.home.container_fourth_suggestion_features_request')
        %br
        %a.button.black.fchat{:href=>"https://groups.google.com/group/instedd-tech"}
          %span= t('views.home.container_fourth_join_our_discussion_list')


      %p
        = t('views.home.container_fourth_get_code_as_developer')
        %br
        %a.button.black.fbulb{:href=>"https://bitbucket.org/instedd/verboice/issues?status=new"}
          %span= t('views.home.container_fourth_our_backlog')



    .clear
    / #clear