config/routes.rb
# Copyright (C) 2010-2012, InSTEDD
#
# This file is part of Verboice.
#
# Verboice is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Verboice is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Verboice.  If not, see <http://www.gnu.org/licenses/>.

require 'api_constraints'

Verboice::Application.routes.draw do

  resources :call_log_recorded_audios, only: [:update]

  resources :channels do
    resources :queued_calls
    member do
      get :call
    end
  end

  resources :nuntium_channels, except: [:show]

  match '/' => 'home#index',  :as => 'home'

  devise_for :accounts

  resources :feeds, controller: :feed_server do
    member do
      get :recordings
      get 'recording/:recording_id', action: :get_recording, as: :recording
    end
  end

  # Register both shallow and deep routes:
  # - Shallow routes allow for easier path helper methods, such as contact_recorded_audios(@contact) instead of project_contact_recorded_audios(@project, @contact)
  # - Deep routes ensure that form_for directives work as expected, so form_for([@project, @contact]) works no matter it is a creation or an update
  [true, false].each do |shallow|
    resources :projects, :shallow => shallow do
      member do
        post :enqueue_call
        put :update_variables
      end
      

      resources :call_flows, except: [:new, :edit] do
        member do
          get :edit_workflow, path: :designer
          put :update_workflow, path: :update_flow
          post :import
          get :export
          get :download_results
          get :oauth
        end
      end

      resources :external_services, except: [:show, :new, :edit] do
        member do
          put :update_manifest
        end
      end

      resources :schedules

      resources :contacts, except: [:show] do
        get :invitable, on: :collection
      end

      resources :resources do
        collection do
          get :find
        end

        resources :localized_resources do
          member do
            post :save_recording
            get :play_recording
            post :save_file
            get :play_file
          end
        end
      end

      resources :feeds
      
      resources :call_logs, :path => :calls, :only => :index do |r|
        collection do
          get :download, to: 'call_logs#download_project_call_logs'
          get :generate_zip
          get :download_zip
        end
      end

      resources :feeds
    end
  end

  resources :call_logs, path: :calls do
    member do
      get :progress
      get 'results/:key', :action => :play_result, :as => 'result'
      get :download_details
    end
    collection do
      get :queued
      put :queued_paused
      put :queued_resumed
      get :download
    end
  end

  namespace :ext do 
    namespace :services do
      resources :pregnancies do
        collection do
          get :manifest
          post :register
          post :progress
        end
      end
    end

    resources :projects do
      resources :reminder_groups, :only => [:index] do
        post :import, :on => :member
      end

      resources :reminder_schedules do
        get :references_data, :on => :collection
        post 'remove_reminder_channel'
        collection do
          get 'channels_autocomplete'
        end
      end

      resources :pregnancy_reminders
    end
  end  
    

  resource :synthesizer do
    get :voices
  end

  namespace :api, defaults: {format: 'json'} do
    match "call" => "calls#call"
    resources :calls, only: [] do
      member do
        match :state
        match :redirect
      end
    end
    get "channels" => "channels#list"
    resources :channels, only: [:create] do
      collection do
        get ":name", :action => "get"
        put ":name", :action => "update"
        delete ":name", :action => "destroy"
      end
    end
    resources :projects, only: [:index] do
      resources :contacts, only: [:index, :create] do
        collection do
          get 'by_address/:address', :action => "show_by_address"
          put 'by_address/:address', :action => "update_by_address"
          put 'all', :action => "update_all"
          delete :unregistration
        end
      end
      resources :schedules, only: [:index, :create] do
        collection do
          get ':name', :action => "show"
          put ':name', :action => "update"
          delete ':name', :action => "destroy"
        end
      end

      resources :reminder_groups, only: [:index, :create, :update, :destroy], shallow: true
    end

    resources :logs, only: [] do
      collection do
        get ':call_id', action: :list
      end
    end

    get '/contacts/:address/call_logs', controller: :call_logs, action: :index
    resources :call_logs, only: [:index, :show]

    get "call_flows" => "call_flows#list"
  end

  namespace :api2, defaults: {format: 'json'} do

    match "call" => "calls#call"
    resources :calls, only: [] do
      member do
        match :state
        match :redirect
      end
    end

    resources :channels, only: [:create, :index] do
      collection do
        get ":name", :action => "get"
        put ":name", :action => "update"
        delete ":name", :action => "destroy"
      end
    end
    resources :projects, only: [:index] do
      resources :contacts, only: [:index, :create] do
        collection do
          get 'by_address/:address', :action => "show_by_address"
          put 'by_address/:address', :action => "update_by_address"
          put 'all', :action => "update_all"
          delete :unregistration
        end
      end
      resources :schedules, only: [:index, :create] do
        collection do
          get ':name', :action => "show"
          put ':name', :action => "update"
          delete ':name', :action => "destroy"
        end
      end

      resources :reminder_groups, only: [:index, :create, :update, :destroy], shallow: true
    end

    resources :logs, only: [] do
      collection do
        get ':call_id', action: :list
      end
    end

    get '/channels/:channel_id/call_logs' => "call_logs#list_by_channel"
    get '/contacts/:address/call_logs', controller: :call_logs, action: :index
    resources :call_logs, only: [:index, :show]

    get "call_flows" => "call_flows#list"

    get "accounts" => "accounts#index"

    post '/auth' => 'sessions#create'

    resources :traffics, only: [:index]
  end

  post 'call_simulator/start'
  post 'call_simulator/resume'

  get 'oauth/google' => 'oauth#google', :as => 'google_oauth'
  match 'oauth/google/callback' => 'oauth#google_callback', :as => 'google_callback_oauth'

  root :to => 'home#index'

  get 'terms_and_conditions', :to => redirect('/')
end

app/controllers/api/projects_controller.rb
# Copyright (C) 2010-2012, InSTEDD
#
# This file is part of Verboice.
#
# Verboice is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Verboice is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Verboice.  If not, see <http://www.gnu.org/licenses/>.
module Api
  class ProjectsController < ApiController

    # GET /api/projects
    def index
      projects = Project.all if current_account.admin?
      projects = current_account.projects if current_account.user?
      render json: projects, root: false
    end
  end
end

app/controllers/api2/projects_controller.rb
# Copyright (C) 2010-2012, InSTEDD
#
# This file is part of Verboice.
#
# Verboice is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Verboice is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Verboice.  If not, see <http://www.gnu.org/licenses/>.
module Api2
  class ProjectsController < Api2Controller

    # GET /api/projects
    def index
      projects = Project.all if api_current_account.admin?
      projects = api_current_account.projects if api_current_account.user?
      render json: projects, root: false
    end
  end
end

app/controllers/projects_controller.rb
# Copyright (C) 2010-2012, InSTEDD
#
# This file is part of Verboice.
#
# Verboice is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Verboice is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Verboice.  If not, see <http://www.gnu.org/licenses/>.

class ProjectsController < ApplicationController
  before_filter :authenticate_account!
  before_filter :load_project, only: [:edit, :update, :destroy, :update_variables]
  before_filter :load_enqueue_call_fields, only: [:show, :enqueue_call]

  

  def index
    @projects = current_account.projects.all
  end

  def show
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = Project.new(params[:project])
    @project.account = current_account

    if @project.save
      redirect_to(project_call_flows_path(@project), :notice => I18n.t("controllers.projects_controller.project_successfully_created", :project_name => @project.name))
    else
      render :action => "new"
    end
  end

  def update
    if @project.update_attributes(params[:project])
      redirect_to(project_path(@project), :notice => I18n.t("controllers.projects_controller.project_successfully_updated", :project_name => @project.name))
    else
      render :action => "edit"
    end
  end

  def enqueue_call
    redirect_to project_path(params[:id]), flash: {error: I18n.t("controllers.projects_controller.you_need_to_select_call_flow")} and return unless params[:call_flow_id].present?

    @channel = current_account.channels.find_by_id(params[:channel_id])
    redirect_to project_path(params[:id]), flash: {error: I18n.t("controllers.projects_controller.you_need_to_select_channel")} and return unless @channel

    addresses = params[:addresses].split(/\n/).map(&:strip).select(&:presence)

    options = {}
    options[:schedule_id] = params[:schedule_id] if params[:schedule_id].present?
    options[:not_before] = "#{params[:not_before_date]} #{params[:not_before_time]}" if params[:not_before_date].present? && params[:not_before].present?
    options[:time_zone] = params[:time_zone] if params[:time_zone].present?
    options[:call_flow_id] = params[:call_flow_id] if params[:call_flow_id].present?
    options[:project_id] = params[:id]
    options[:vars] = params[:vars]

    DateTime.parse(options[:not_before]) rescue redirect_to project_path(params[:id]), flash: {error: I18n.t("controllers.projects_controller.enter_valid_date")} and return if options[:not_before]

    addresses = curated_addresses(addresses)
    addresses.each do |address|
      @channel.call(address.strip, options)
    end

    redirect_to project_path(params[:id]), {:notice => I18n.t("controllers.projects_controller.enqueued_call_to_on_channel", :pluralize => pluralize(addresses.count, 'address'), :channel_name => @channel.name)}
  end

  def destroy
    @project.destroy
    redirect_to(projects_url, :notice => I18n.t("controllers.projects_controller.project_successfully_deleted", :project_name => @project.name))
  end

  def update_variables
    if @project.update_attributes(params[:project])
      redirect_to project_contacts_path(@project), notice: I18n.t("controllers.projects_controller.columns_successfully_updated")
    else
      redirect_to project_contacts_path(@project), flash: { error: I18n.t("controllers.projects_controller.error_updating_columns")}
    end
  end

  private

  def load_project
    @project = current_account.projects.find(params[:id])
  end

  def load_enqueue_call_fields
    @channels = current_account.channels
    @project = current_account.projects.includes(:call_flows).find(params[:id])
    @schedules = @project.schedules.enabled
    @call_flows = @project.call_flows.includes(:channels).includes(:queued_calls)
    @project_channels = @call_flows.collect(&:channels).flatten.to_set
    @queued_calls = @call_flows.collect(&:queued_calls).flatten
    @call_logs = @project.call_logs
  end

  def curated_addresses(addresses)
    # build a hash from contact_id to all his addresses 
    # eg. { 1 => ['123','456'], 2 => ['789'] }
    all_contacts = Hash.new { |hash,key| hash[key] = [] }
    all_contacts = @project.contact_addresses.order(:id).inject(all_contacts) do |contacts, contact_address|
      contacts[contact_address.contact_id] << contact_address.address
      contacts
    end
    # now build a hash from every contact's addresses to all his addresses
    # eg. { '123' => ['123', '456'], '456' => ['123', '456'], '789' => ['789'] }
    all_addresses = all_contacts.values.inject({}) do |all_addresses, contact_addresses|
      contact_addresses.each do |contact_address|
        all_addresses[contact_address] = contact_addresses
      end
      all_addresses
    end

    # curate the addresses so that there is only one entry for each contact in
    # the original list, and that entry is the contact's first registered address
    known_addresses = Set.new
    addresses.inject([]) do |curated, address|
      unless known_addresses.include?(address)
        contact_addresses = all_addresses[address]
        if contact_addresses.nil?
          known_addresses << address
          curated << address
        else
          known_addresses.merge(contact_addresses)
          curated << contact_addresses.first
        end
      end
      curated
    end
  end
end

app/helpers/project_helper.rb
# Copyright (C) 2010-2012, InSTEDD
#
# This file is part of Verboice.
#
# Verboice is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Verboice is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Verboice.  If not, see <http://www.gnu.org/licenses/>.

module ProjectHelper

  def project_languages_json(project)
    project.languages.map { |lang| {key: lang['language'], value: LanguageList::LanguageInfo.find(lang['language']).name} }.to_json
  end

  def call_flows_options(project)
    all_call_flow = [t('views.projects.call_logs.index.label.all_call_flow'), nil]
    options = project.call_flows.map { |c| [c.name, c.id] }.insert 0, all_call_flow
    options
  end
end

app/views/projects/_enqueue_new_call.html.haml
.box.w30.right.lmargin.enqueue_new_call
  %h2= t('views.projects._enqueue_new_call.title')
  %p.desc= t('views.projects._enqueue_new_call.desc')
  = form_tag enqueue_call_project_path, :method => 'POST' do
    %p
      = label_tag :call_flow_id, t('views.projects._enqueue_new_call.label.call_flow')
      %br/
      = select_tag :call_flow_id, options_from_collection_for_select(call_flows, 'id', 'name'), :prompt => t('views.projects._enqueue_new_call.label.select_call_flow'), :class => 'w30'
    %p
      = label_tag :channel_id, t('projects._enqueue_new_call.label.channel')
      %br/
      = select_tag :channel_id, options_from_collection_for_select(channels, 'id', 'name'), :prompt => t('views.projects._enqueue_new_call.label.select_channel'), :class => 'w30'
    %p
      = label_tag :schedule_id, t('projects._enqueue_new_call.label.schedule')
      %br/
      = select_tag :schedule_id, options_from_collection_for_select(schedules, 'id', 'name'), :prompt => t('views.projects._enqueue_new_call.label.select_schedule'), :class => 'w30'
    %p
      = check_box_tag :not_before
      = label_tag :not_before, t('views.projects._enqueue_new_call.label.not_before')
      %br/
      = text_field_tag :not_before_date, '', :class => "ux-custom-datepicker ux-datepicker w10"
      = text_field_tag :not_before_time, '00:00', :class => 'w10', :alt => 'time'
    %p
      = label_tag :time_zone, t('views.projects._enqueue_new_call.label.on_time_zone')
      %br/
      = select_tag :time_zone, time_zone_options_for_select(project.time_zone), :class => 'w30'
    %p
      = label_tag :language, t('views.projects._enqueue_new_call.label.language')
      %br/
      = select_tag :language, options_for_select(project.languages.map { |lang| [LanguageList::LanguageInfo.find(lang['language']).name, lang['language']] }), prompt: 'None specified', name: 'vars[language]'
    - if project.project_variables.any?
      %p
        .ux-collapsible.collapsed
          %span
            %a.arrow{href: "#"}
              = label_tag :variables, "#{t('views.projects._enqueue_new_call.label.variables')}:"
          .ux-content
            - project.project_variables.each do |var|
              %br/
              = label_tag var.name, var.name.downcase
              %br/
              = text_field_tag var.name, '', name: "vars[#{var.name}]"
            - project.external_services.each do |service|
              - service.global_variables.each do |var|
                %br/
                = label_tag var.name, var.display_name
                %br/
                = text_field_tag var.name, '', name: "vars[#{var.name}]"
    %p
      = label_tag :addresses, t('views.projects._enqueue_new_call.label.phone_numbers')
      %br/
      %span.desc= t('views.projects._enqueue_new_call.label.desc')
      %p
        = text_area_tag :addresses, nil, :placeholder => "555-1000", :rows => 10, :class => 'w30'
    %p
      = button_tag t('views.projects._enqueue_new_call.action.enqueue_calls'), :class => 'orange'

app/views/projects/_form.haml
- content_for :head do
  :javascript
    $(function() { initProjectSettings(#{@project.default_language.to_json}, #{@project.languages.to_json}, #{@project.synthesizer.voices.to_json}); });

= form_for(@project, :builder => InsteddFormBuilder) do |f|
  - if @project.errors.any?
    #error_explanation
      %h2
        = t('views.projects._form.errors.prohibited', :count => @project.errors.count)
      %ul
        - @project.errors.full_messages.each do |msg|
          %li= msg

  %br

  %h1= t('views.projects._form.label.properties')

  = f.text_field :name, :label => t('views.projects._form.label.name')
  = f.time_zone_select :time_zone, ActiveSupport::TimeZone.all, :label => t('views.projects._form.label.time_zone')
  = f.check_box :store_call_log_entries, :label => t('views.projects._form.label.store_call_log_details')

  %hr

  %br
  %br

  %h1= t('views.projects._form.label.languages')

  = f.label :default_language, "#{t('views.projects._form.label.default_language')}"
  %br
  %select.w30{ko(value: 'defaultLanguage', options: 'languages', optionsText: "'label'", optionsValue: "'value'"), name: 'project[default_language]'}

  %br
  %br
  = f.select :tts_engine, options_for_select([['Built in', 'built-in'], ['iSpeech', 'ispeech']], @project.tts_engine), label: 'Text-to-speech Engine'
  = f.text_field :tts_ispeech_api_key, label: 'iSpeech API key'

  = f.label :languages, t('views.projects._form.label.supported_languages')
  %br

  %ul.clist.w30
    /ko foreach: languages
    %li
      %input{ko(value: 'value'), type: 'hidden', name: 'project[languages][][language]'}
      %span.w15{ko(text: 'description')}
      %select.w15{ko(value: 'voice', options: 'voices()', optionsText: "'description'", optionsValue: "'id'"), name: 'project[languages][][voice]'}
      %button.clist-remove{ko(click: '$root.removeLanguage')}
    //ko
    %li
      %input#add_language.ux-type{ko(value: 'newLanguage', valueUpdate: 'afterkeydown', event: {keydown: 'keydown'}), type: 'text', placeholder: "#{t('views.projects._form.label.add_new_language')}"}
      %button#add_language_button.clist-add{ko(click: 'addLanguage')}

  %br

  %hr

  %br
  %br

  %h1= t('views.projects._form.label.status_callback')

  = f.text_field :status_callback_url, :label => t('views.projects._form.label.url')
  = f.text_field :status_callback_url_user, :label => t('views.projects._form.label.user'), :autocomplete => 'off'
  = f.password_field :status_callback_url_password, :label => t('views.projects._form.label.password'), :autocomplete => 'off'

  %hr

  - if @project.new_record?
    %button.white{:type => "submit"}= t('views.projects._form.action.save')
    = link_to t('views.projects._form.action.cancel'), projects_path, :class => "button white cancel", :style => 'top: 1px;'
  - else
    %button.white{:type => "submit"}= t('views.projects._form.action.update')
    = link_to t('views.projects._form.action.cancel'), project_path(@project), :class => "button white cancel", :style => 'top: 1px;'

app/views/projects/edit.haml
= render 'shared/project_tabs_and_title', :project => @project

= render 'form'

app/views/projects/index.haml
%h2= t('views.projects.index.title')

%br
.tablewrapp.w60
  %table.GralTable.TwoColumn.CleanTable.ItemsTable{:class => ('empty' if @projects.empty?)}
    %tr
      %th= t('views.projects.index.label.my_projects')
      %th
    - if @projects.empty?
      %tr
        %td.EmptyFolder{:colspan => 100}
          %br
          = t('views.projects.index.label.no_projects')
          %br
          = link_button_to t('views.projects.index.action.create_project'), new_project_path, :class => 'EmptyAddButton button cadd'
    - else
      - @projects.each do |project|
        %tr.link{'data-url' => project_path(project)}
          %td= project.name
          %td
            %button.farrow{:type => :button}
      %tr.link{'data-url' => new_project_path}
        %td= t('views.projects.index.action.create_project')
        %td
          %button.cadd

app/views/projects/new.haml
%h2= t('views.projects.new.title')
= render 'form'

app/views/projects/show.haml
= render 'shared/project_tabs_and_title', :project => @project

= render 'enqueue_new_call', :project => @project, :call_flows => @call_flows, :channels => @channels, :schedules => @schedules

%h1= t('views.projects.show.title')
%p.desc= t('views.projects.show.desc')

.sbox.grey.StateDisplay.w30
  .values
    .U
      %span.big= @call_logs.size
      %span= "#{@call_logs.size == 1 ? t('views.projects.show.label.call') : t('views.projects.show.label.calls')} #{t('views.projects.show.label.registered')}"

  = link_to t('views.projects.show.action.download_csv'), download_project_call_logs_path(@project, format: :csv), class: 'button white'

%br/

%h1= t('views.projects.show.concurrent_call')
%p.desc= t('views.projects.show.concurrent_call_detail')

.sbox.grey.StateDisplay.w30
  .values{style: "width:100%;padding-left:2px;"}
    .U
      %span.big= @project.number_of_active_call
      %span=  t('views.projects.show.label.active_call')
%br/


%hr/
%br/

%h1= t('views.projects.show.label.properties')

%ul.call-properties.left
  %li
    .i48grad-call-flow
    %div
      %span="#{pluralize @call_flows.size, 'Call flow'} #{t('views.projects.show.label.in_this_project')}"
    = link_to t('views.projects.show.action.edit_call_flows'), project_call_flows_path(@project), :class => "button faccept"
  %li
    .i48grad-channel
    %div
      %span= "#{pluralize @project_channels.size, 'channel'} #{t('views.projects.show.label.in_this_project')}"
    = link_to t('views.projects.show.action.manage_channels'), channels_path, :class => "button faccept"

  %li
    .i48grad-time
    %div
      %span= pluralize @queued_calls.size, 'queued call'
    = link_to t('views.projects.show.action.view_calls'), queued_call_logs_path, :class => "button faccept"

%br{ :clear => 'left'}

= link_to t('views.projects.show.action.edit_settings'), edit_project_path(@project), :class => "button faccept"
%hr

= link_to t('views.projects.show.action.delete_this_project'), @project, :confirm => "#{t('views.projects.show.action.confirm_delete')} #{@project.name}?", :method => :delete, :class => "button fdelete"
.clear